# Generated by Django 2.2.6 on 2019-11-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_last_fetched_zillow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_num', models.CharField(blank=True, max_length=30, null=True)),
                ('zpid', models.CharField(max_length=255, unique=True)),
                ('estimated_rent_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estimated_rent_price_currency', models.CharField(max_length=10)),
                ('last_estimated', models.DateField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('zillow_url', models.URLField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_set', to='location.Location')),
            ],
        ),
    ]
