# Generated by Django 2.2.6 on 2019-11-09 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='number_of_bed',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
