# Generated by Django 2.2.6 on 2019-11-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20191109_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='estimated_rent_price_currency',
        ),
    ]
