# Generated by Django 2.2.7 on 2019-11-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_apartment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_zillow_listing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='estimated_rent_price_currency',
            field=models.CharField(blank=True, default='$', max_length=10, null=True),
        ),
    ]
