# Generated by Django 2.2.6 on 2019-11-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20191109_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_zillow_listing',
            field=models.BooleanField(default=True),
        ),
    ]
