# Generated by Django 2.2.6 on 2019-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_remove_apartment_is_zillow_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='suite_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
