# Generated by Django 2.2.7 on 2019-11-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20191112_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='suite_num',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
