# Generated by Django 2.2.6 on 2019-11-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20191114_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='c_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
