# Generated by Django 2.2.7 on 2019-11-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_apartment_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(default='', null=None),
        ),
    ]
