# Generated by Django 2.2.7 on 2019-11-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_apartment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
