# Generated by Django 2.2.7 on 2019-11-17 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_auto_20191117_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bed',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bedrooms'),
        ),
    ]
