# Generated by Django 2.2.7 on 2019-11-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_auto_20191117_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('suite_num', 'location')},
        ),
    ]
