# Generated by Django 2.2.7 on 2019-11-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_auto_20191118_1728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set(),
        ),
    ]
