# Generated by Django 2.2.7 on 2019-11-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_auto_20191118_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('suite_num', 'location')},
        ),
    ]
