# Generated by Django 2.2.7 on 2019-11-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20191118_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Apartment has been rented?'),
        ),
    ]
