# Generated by Django 2.2.8 on 2019-12-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_auto_20191130_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
