# Generated by Django 2.2.8 on 2019-12-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0021_location_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=100)),
                ('note', models.TextField()),
                ('access_granted', models.BooleanField(default=False)),
                ('allow_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deny_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_set', to='location.Apartment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
