# Generated by Django 2.2.6 on 2019-10-25 18:07

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStreetSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('last_update', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='./map/static/map')),
                ('geom', djgeojson.fields.PointField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.CraigslistLocation')),
            ],
        ),
    ]
