# Generated by Django 2.2.6 on 2019-10-16 00:24

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [("map", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="citystreetspot",
            name="geom",
            field=djgeojson.fields.PolygonField(),
        )
    ]
