# Generated by Django 2.2.6 on 2019-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citystreetspot',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
