# Generated by Django 2.2.6 on 2019-10-16 01:08

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [("map", "0002_auto_20191015_2024")]

    operations = [
        migrations.AlterField(
            model_name="citystreetspot",
            name="geom",
            field=djgeojson.fields.PointField(),
        )
    ]
