# Generated by Django 2.2.6 on 2019-10-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191028_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citystreetspot',
            name='id',
        ),
        migrations.AlterField(
            model_name='citystreetspot',
            name='c_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.CraigslistLocation'),
        ),
    ]
