# Generated by Django 2.2.6 on 2019-10-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20191028_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citystreetspot',
            name='picture',
            field=models.ImageField(upload_to='./map/static/map'),
        ),
    ]
