# Generated by Django 2.2.6 on 2019-10-21 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20191016_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='citystreetspot',
            name='c_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
