# Generated by Django 2.2.6 on 2019-10-21 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_citystreetspot_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citystreetspot',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
