# Generated by Django 2.2.6 on 2019-10-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
