# Generated by Django 2.2.6 on 2019-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
