# Generated by Django 2.2.6 on 2019-10-15 18:52

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="current_location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("T", "Tenant"), ("R", "Renter"), ("L", "Landlord")],
                default="R",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="work_location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
