# Generated by Django 2.2.1 on 2019-11-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('mainapp', '0002_siteuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='search.CraigslistLocation'),
        ),
    ]
