# Generated by Django 2.2.6 on 2019-10-16 22:10

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191015_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[(mainapp.models.UserType('T'), 'Tenant'), (mainapp.models.UserType('R'), 'Renter'), (mainapp.models.UserType('L'), 'Landlord')], default=mainapp.models.UserType('R'), max_length=2),
        ),
    ]
