# Generated by Django 2.2.1 on 2019-11-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_siteuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='location.Location'),
        ),
    ]
