# Generated by Django 2.2.6 on 2019-11-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191102_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='user_type',
        ),
    ]
