# Generated by Django 2.2.6 on 2019-11-20 14:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_siteuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
    ]
