# Generated by Django 2.2.6 on 2019-11-04 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated',
        ),
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
