# Generated by Django 2.2.8 on 2019-12-05 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CraigslistLocation',
        ),
        migrations.DeleteModel(
            name='LastRetrievedData',
        ),
    ]
