# Generated by Django 2.2.4 on 2019-10-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("search", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="LastRetrievedData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=200, unique=True)),
                ("time", models.DateTimeField()),
            ],
        )
    ]
