# Generated by Django 2.2.4 on 2019-10-15 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("search", "0002_lastretrieveddata")]

    operations = [
        migrations.AlterField(
            model_name="lastretrieveddata",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="last retrieval"
            ),
        )
    ]
